In [1]:
%pip install pandas numpy networkx scikit-learn plotly seaborn matplotlib networkx plotly plotly-express

Requirement already satisfied: pandas in e:\ekatarimalkernel\lib\site-packages (3.0.2)
Requirement already satisfied: numpy in e:\ekatarimalkernel\lib\site-packages (2.4.4)
Requirement already satisfied: networkx in e:\ekatarimalkernel\lib\site-packages (3.6.1)
Requirement already satisfied: scikit-learn in e:\ekatarimalkernel\lib\site-packages (1.8.0)
Requirement already satisfied: plotly in e:\ekatarimalkernel\lib\site-packages (6.7.0)
Requirement already satisfied: seaborn in e:\ekatarimalkernel\lib\site-packages (0.13.2)
Requirement already satisfied: matplotlib in e:\ekatarimalkernel\lib\site-packages (3.10.9)
Requirement already satisfied: plotly-express in e:\ekatarimalkernel\lib\site-packages (0.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in e:\ekatarimalkernel\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in e:\ekatarimalkernel\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: scipy>=1.10.0 in e:\ekatarimalkernel\lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in e:\ekatarimalkernel\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in e:\ekatarimalkernel\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: narwhals>=1.15.1 in e:\ekatarimalkernel\lib\site-packages (from plotly) (2.21.0)
Requirement already satisfied: packaging in e:\ekatarimalkernel\lib\site-packages (from plotly) (26.2)
Requirement already satisfied: contourpy>=1.0.1 in e:\ekatarimalkernel\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in e:\ekatarimalkernel\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in e:\ekatarimalkernel\lib\site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in e:\ekatarimalkernel\lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: pillow>=8 in e:\ekatarimalkernel\lib\site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in e:\ekatarimalkernel\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: statsmodels>=0.9.0 in e:\ekatarimalkernel\lib\site-packages (from plotly-express) (0.14.6)
Requirement already satisfied: patsy>=0.5 in e:\ekatarimalkernel\lib\site-packages (from plotly-express) (1.0.2)
Requirement already satisfied: six>=1.5 in e:\ekatarimalkernel\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import numpy as np
import json
import os
import plotly.express as px
import seaborn as sns
import matplotlib.pyplot as plt
import networkx as nx
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

import warnings
warnings.filterwarnings('ignore')

print("[SYSTEM] Environment ready. All libraries imported.")

[SYSTEM] Environment ready. All libraries imported.

In [3]:
data = {
    "Product": ["TV","Laptop","TV","Speaker","Tablet","Laptop","TV","Speaker","Tablet","TV"],
    "City": ["Kathmandu","Kathmandu","Pokhara","Biratnagar","Kathmandu","Pokhara","Kathmandu","Biratnagar","Kathmandu","Pokhara"],
    "Store_Address": [
        "New Road 12",
        "Durbar Marg 5",
        "Lakeside 21",
        "Main Road 8",
        "Putalisadak 12",
        "Chipledhunga 33",
        "Thamel 5",
        "Biratnagar Bazaar 8",
        "Baneshwor 12",
        "Mahendrapool 21"
    ],
    "Season": ["Q1","Q2","Q1","Q3","Q1","Q4","Q1","Q3","Q2","Q1"],
    "Sales": [12000,15000,11000,5000,8000,14000,13000,6000,9000,12500],
    "Quantity": [12,15,11,5,8,14,13,6,9,12]
}

df = pd.DataFrame(data)
df

   Product        City        Store_Address Season  Sales  Quantity
0       TV   Kathmandu          New Road 12     Q1  12000        12
1   Laptop   Kathmandu        Durbar Marg 5     Q2  15000        15
2       TV     Pokhara          Lakeside 21     Q1  11000        11
3  Speaker  Biratnagar          Main Road 8     Q3   5000         5
4   Tablet   Kathmandu       Putalisadak 12     Q1   8000         8
5   Laptop     Pokhara      Chipledhunga 33     Q4  14000        14
6       TV   Kathmandu             Thamel 5     Q1  13000        13
7  Speaker  Biratnagar  Biratnagar Bazaar 8     Q3   6000         6
8   Tablet   Kathmandu         Baneshwor 12     Q2   9000         9
9       TV     Pokhara      Mahendrapool 21     Q1  12500        12

In [4]:
df.head(10)

   Product        City        Store_Address Season  Sales  Quantity
0       TV   Kathmandu          New Road 12     Q1  12000        12
1   Laptop   Kathmandu        Durbar Marg 5     Q2  15000        15
2       TV     Pokhara          Lakeside 21     Q1  11000        11
3  Speaker  Biratnagar          Main Road 8     Q3   5000         5
4   Tablet   Kathmandu       Putalisadak 12     Q1   8000         8
5   Laptop     Pokhara      Chipledhunga 33     Q4  14000        14
6       TV   Kathmandu             Thamel 5     Q1  13000        13
7  Speaker  Biratnagar  Biratnagar Bazaar 8     Q3   6000         6
8   Tablet   Kathmandu         Baneshwor 12     Q2   9000         9
9       TV     Pokhara      Mahendrapool 21     Q1  12500        12

In [5]:
df.columns
df.dtypes

Product            str
City               str
Store_Address      str
Season             str
Sales            int64
Quantity         int64
dtype: object

In [6]:
df["Sales"].mean()
df["Sales"].max()

np.int64(15000)

In [7]:
q1_slice = df[df["Season"] == "Q1"]
q1_slice

  Product       City    Store_Address Season  Sales  Quantity
0      TV  Kathmandu      New Road 12     Q1  12000        12
2      TV    Pokhara      Lakeside 21     Q1  11000        11
4  Tablet  Kathmandu   Putalisadak 12     Q1   8000         8
6      TV  Kathmandu         Thamel 5     Q1  13000        13
9      TV    Pokhara  Mahendrapool 21     Q1  12500        12

In [8]:
dice_view = df[
    (df["Product"] == "TV") &
    (df["City"] == "Kathmandu") &
    (df["Season"] == "Q1")
]
dice_view

  Product       City Store_Address Season  Sales  Quantity
0      TV  Kathmandu   New Road 12     Q1  12000        12
6      TV  Kathmandu      Thamel 5     Q1  13000        13

In [9]:
# City-level aggregation
city_level = df.groupby("City")["Sales"].sum()
city_level

# Drill down to Store-level
store_level = df.groupby(["City","Store_Address"])["Sales"].sum()
store_level

City        Store_Address
Biratnagar  Biratnagar Bazaar 8     6000
            Main Road 8             5000
Kathmandu   Baneshwor 12            9000
            Durbar Marg 5          15000
            New Road 12            12000
            Putalisadak 12          8000
            Thamel 5               13000
Pokhara     Chipledhunga 33        14000
            Lakeside 21            11000
            Mahendrapool 21        12500
Name: Sales, dtype: int64

In [10]:
# Seasonal totals
season_sales = df.groupby("Season")["Sales"].sum()
season_sales

# Yearly total (sum of all seasons)
yearly_sales = df["Sales"].sum()
yearly_sales

np.int64(105500)